package mps.samples.architecture.base.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class ConceptualArchitecture_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "name", "Conceptual Architecture");
  }
}
