package mps.samples.architecture.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class Architecture_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "name", "Test");
  }
}
