package mps.samples.architecture.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Architecture_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("e04769b2-a289-407b-ae3f-4c93ac019447(mps.samples.architecture)");

  public static Language get() {
    return (Language)MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
