package mps.samples.architecture.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Component extends BaseConcept implements INamedConcept {
  public static final String concept = "mps.samples.architecture.structure.Component";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";

  public Component(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(Component.NAME);
  }

  public void setName(String value) {
    this.setProperty(Component.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(Component.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Component.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Component.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Component.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Component.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Component.VIRTUAL_PACKAGE, value);
  }


  public static Component newInstance(SModel sm, boolean init) {
    return (Component)SModelUtil_new.instantiateConceptDeclaration("mps.samples.architecture.structure.Component", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Component newInstance(SModel sm) {
    return Component.newInstance(sm, false);
  }

}
