package mps.samples.architecture.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Connection extends BaseConcept {
  public static final String concept = "mps.samples.architecture.structure.Connection";
  public static final String REQUIRED_INSTANCE = "requiredInstance";

  public Connection(SNode node) {
    super(node);
  }

  public Instance getRequiredInstance() {
    return (Instance)this.getReferent(Instance.class, Connection.REQUIRED_INSTANCE);
  }

  public void setRequiredInstance(Instance node) {
    super.setReferent(Connection.REQUIRED_INSTANCE, node);
  }


  public static Connection newInstance(SModel sm, boolean init) {
    return (Connection)SModelUtil_new.instantiateConceptDeclaration("mps.samples.architecture.structure.Connection", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Connection newInstance(SModel sm) {
    return Connection.newInstance(sm, false);
  }

}
