package mps.samples.architecture.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.Type;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class JavaDataStructureMember extends DataStructureMember {
  public static final String concept = "mps.samples.architecture.structure.JavaDataStructureMember";
  public static final String JAVA_TYPE = "javaType";

  public JavaDataStructureMember(SNode node) {
    super(node);
  }

  public Type getJavaType() {
    return (Type)this.getChild(Type.class, JavaDataStructureMember.JAVA_TYPE);
  }

  public void setJavaType(Type node) {
    super.setChild(JavaDataStructureMember.JAVA_TYPE, node);
  }

  public static JavaDataStructureMember newInstance(SModel sm, boolean init) {
    return (JavaDataStructureMember)SModelUtil_new.instantiateConceptDeclaration("mps.samples.architecture.structure.JavaDataStructureMember", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static JavaDataStructureMember newInstance(SModel sm) {
    return JavaDataStructureMember.newInstance(sm, false);
  }
}
