package mps.samples.architecture.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class OneToN extends Cardinality {
  public static final String concept = "mps.samples.architecture.structure.OneToN";

  public OneToN(SNode node) {
    super(node);
  }

  public static OneToN newInstance(SModel sm, boolean init) {
    return (OneToN)SModelUtil_new.instantiateConceptDeclaration("mps.samples.architecture.structure.OneToN", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static OneToN newInstance(SModel sm) {
    return OneToN.newInstance(sm, false);
  }

}
