package mps.samples.architecture.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class PublishedReplicatedItem extends BaseConcept {
  public static final String concept = "mps.samples.architecture.structure.PublishedReplicatedItem";
  public static final String REPLICATED_ITEM = "replicatedItem";
  public static final String REPLICATION_PROPERTY = "replicationProperty";

  public PublishedReplicatedItem(SNode node) {
    super(node);
  }

  public ReplicatedItem getReplicatedItem() {
    return (ReplicatedItem)this.getReferent(ReplicatedItem.class, PublishedReplicatedItem.REPLICATED_ITEM);
  }

  public void setReplicatedItem(ReplicatedItem node) {
    super.setReferent(PublishedReplicatedItem.REPLICATED_ITEM, node);
  }

  public int getReplicationPropertiesCount() {
    return this.getChildCount(PublishedReplicatedItem.REPLICATION_PROPERTY);
  }

  public Iterator<ReplicationProperty> replicationProperties() {
    return this.children(ReplicationProperty.class, PublishedReplicatedItem.REPLICATION_PROPERTY);
  }

  public List<ReplicationProperty> getReplicationProperties() {
    return this.getChildren(ReplicationProperty.class, PublishedReplicatedItem.REPLICATION_PROPERTY);
  }

  public void addReplicationProperty(ReplicationProperty node) {
    this.addChild(PublishedReplicatedItem.REPLICATION_PROPERTY, node);
  }

  public void insertReplicationProperty(ReplicationProperty prev, ReplicationProperty node) {
    this.insertChild(prev, PublishedReplicatedItem.REPLICATION_PROPERTY, node);
  }

  public static PublishedReplicatedItem newInstance(SModel sm, boolean init) {
    return (PublishedReplicatedItem)SModelUtil_new.instantiateConceptDeclaration("mps.samples.architecture.structure.PublishedReplicatedItem", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static PublishedReplicatedItem newInstance(SModel sm) {
    return PublishedReplicatedItem.newInstance(sm, false);
  }
}
