package mps.sample.architecture.interfaces.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Interfaces_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("8334936c-9f55-44c5-b5d4-cb373f5d6480(mps.sample.architecture.interfaces)");

  public static Language get() {
    return (Language)MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
