package mps.sample.architecture.interfaces.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import mps.samples.architecture.types.structure.Type;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class MessageParameter extends BaseConcept implements INamedConcept {
  public static final String concept = "mps.sample.architecture.interfaces.structure.MessageParameter";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String TYPE = "type";

  public MessageParameter(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(MessageParameter.NAME);
  }

  public void setName(String value) {
    this.setProperty(MessageParameter.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(MessageParameter.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(MessageParameter.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(MessageParameter.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(MessageParameter.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(MessageParameter.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(MessageParameter.VIRTUAL_PACKAGE, value);
  }

  public Type getType() {
    return (Type)this.getChild(Type.class, MessageParameter.TYPE);
  }

  public void setType(Type node) {
    super.setChild(MessageParameter.TYPE, node);
  }

  public static MessageParameter newInstance(SModel sm, boolean init) {
    return (MessageParameter)SModelUtil_new.instantiateConceptDeclaration("mps.sample.architecture.interfaces.structure.MessageParameter", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static MessageParameter newInstance(SModel sm) {
    return MessageParameter.newInstance(sm, false);
  }
}
