package mps.samples.architecture.base.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ApplicationArchitecture extends BaseConcept implements INamedConcept {
  public static final String concept = "mps.samples.architecture.base.structure.ApplicationArchitecture";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String NAMESPACE = "namespace";

  public ApplicationArchitecture(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(ApplicationArchitecture.NAME);
  }

  public void setName(String value) {
    this.setProperty(ApplicationArchitecture.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(ApplicationArchitecture.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(ApplicationArchitecture.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(ApplicationArchitecture.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(ApplicationArchitecture.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(ApplicationArchitecture.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(ApplicationArchitecture.VIRTUAL_PACKAGE, value);
  }

  public int getNamespacesCount() {
    return this.getChildCount(ApplicationArchitecture.NAMESPACE);
  }

  public Iterator<NamespaceForApplicationArchitecture> namespaces() {
    return this.children(NamespaceForApplicationArchitecture.class, ApplicationArchitecture.NAMESPACE);
  }

  public List<NamespaceForApplicationArchitecture> getNamespaces() {
    return this.getChildren(NamespaceForApplicationArchitecture.class, ApplicationArchitecture.NAMESPACE);
  }

  public void addNamespace(NamespaceForApplicationArchitecture node) {
    this.addChild(ApplicationArchitecture.NAMESPACE, node);
  }

  public void insertNamespace(NamespaceForApplicationArchitecture prev, NamespaceForApplicationArchitecture node) {
    this.insertChild(prev, ApplicationArchitecture.NAMESPACE, node);
  }

  public static ApplicationArchitecture newInstance(SModel sm, boolean init) {
    return (ApplicationArchitecture)SModelUtil_new.instantiateConceptDeclaration("mps.samples.architecture.base.structure.ApplicationArchitecture", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ApplicationArchitecture newInstance(SModel sm) {
    return ApplicationArchitecture.newInstance(sm, false);
  }
}
