package mps.samples.architecture.base.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class DeprecatedInterface extends BaseConcept implements INamedConcept {
  public static final String concept = "mps.samples.architecture.base.structure.DeprecatedInterface";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";

  public DeprecatedInterface(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(DeprecatedInterface.NAME);
  }

  public void setName(String value) {
    this.setProperty(DeprecatedInterface.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(DeprecatedInterface.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(DeprecatedInterface.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(DeprecatedInterface.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(DeprecatedInterface.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(DeprecatedInterface.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(DeprecatedInterface.VIRTUAL_PACKAGE, value);
  }

  public static DeprecatedInterface newInstance(SModel sm, boolean init) {
    return (DeprecatedInterface)SModelUtil_new.instantiateConceptDeclaration("mps.samples.architecture.base.structure.DeprecatedInterface", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static DeprecatedInterface newInstance(SModel sm) {
    return DeprecatedInterface.newInstance(sm, false);
  }
}
