package mps.samples.architecture.base.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ProvidedInterface extends BaseConcept implements INamedConcept {
  public static final String concept = "mps.samples.architecture.base.structure.ProvidedInterface";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String INTERFACE = "interface";

  public ProvidedInterface(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(ProvidedInterface.NAME);
  }

  public void setName(String value) {
    this.setProperty(ProvidedInterface.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(ProvidedInterface.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(ProvidedInterface.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(ProvidedInterface.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(ProvidedInterface.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(ProvidedInterface.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(ProvidedInterface.VIRTUAL_PACKAGE, value);
  }

  public DeprecatedInterface getInterface() {
    return (DeprecatedInterface)this.getReferent(DeprecatedInterface.class, ProvidedInterface.INTERFACE);
  }

  public void setInterface(DeprecatedInterface node) {
    super.setReferent(ProvidedInterface.INTERFACE, node);
  }

  public static ProvidedInterface newInstance(SModel sm, boolean init) {
    return (ProvidedInterface)SModelUtil_new.instantiateConceptDeclaration("mps.samples.architecture.base.structure.ProvidedInterface", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ProvidedInterface newInstance(SModel sm) {
    return ProvidedInterface.newInstance(sm, false);
  }
}
