package mps.samples.architecture.types.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ArrayType extends Type {
  public static final String concept = "mps.samples.architecture.types.structure.ArrayType";
  public static final String TYPE = "type";

  public ArrayType(SNode node) {
    super(node);
  }

  public Type getType() {
    return (Type)this.getChild(Type.class, ArrayType.TYPE);
  }

  public void setType(Type node) {
    super.setChild(ArrayType.TYPE, node);
  }

  public static ArrayType newInstance(SModel sm, boolean init) {
    return (ArrayType)SModelUtil_new.instantiateConceptDeclaration("mps.samples.architecture.types.structure.ArrayType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ArrayType newInstance(SModel sm) {
    return ArrayType.newInstance(sm, false);
  }
}
