package mps.samples.architecture.types.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class IntType extends Type {
  public static final String concept = "mps.samples.architecture.types.structure.IntType";

  public IntType(SNode node) {
    super(node);
  }

  public static IntType newInstance(SModel sm, boolean init) {
    return (IntType)SModelUtil_new.instantiateConceptDeclaration("mps.samples.architecture.types.structure.IntType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static IntType newInstance(SModel sm) {
    return IntType.newInstance(sm, false);
  }
}
