package mps.samples.architecture.types.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class StringType extends Type {
  public static final String concept = "mps.samples.architecture.types.structure.StringType";

  public StringType(SNode node) {
    super(node);
  }

  public static StringType newInstance(SModel sm, boolean init) {
    return (StringType)SModelUtil_new.instantiateConceptDeclaration("mps.samples.architecture.types.structure.StringType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static StringType newInstance(SModel sm) {
    return StringType.newInstance(sm, false);
  }
}
