package mps.samples.architecture.types.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class StructReference extends Type {
  public static final String concept = "mps.samples.architecture.types.structure.StructReference";
  public static final String STRUCT = "struct";

  public StructReference(SNode node) {
    super(node);
  }

  public Struct getStruct() {
    return (Struct)this.getReferent(Struct.class, StructReference.STRUCT);
  }

  public void setStruct(Struct node) {
    super.setReferent(StructReference.STRUCT, node);
  }

  public static StructReference newInstance(SModel sm, boolean init) {
    return (StructReference)SModelUtil_new.instantiateConceptDeclaration("mps.samples.architecture.types.structure.StructReference", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static StructReference newInstance(SModel sm) {
    return StructReference.newInstance(sm, false);
  }
}
