package mps.samples.architecture.types.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class StructMember extends BaseConcept implements INamedConcept {
  public static final String concept = "mps.samples.architecture.types.structure.StructMember";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String TYPE = "type";

  public StructMember(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(StructMember.NAME);
  }

  public void setName(String value) {
    this.setProperty(StructMember.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(StructMember.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(StructMember.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(StructMember.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(StructMember.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(StructMember.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(StructMember.VIRTUAL_PACKAGE, value);
  }

  public Type getType() {
    return (Type)this.getChild(Type.class, StructMember.TYPE);
  }

  public void setType(Type node) {
    super.setChild(StructMember.TYPE, node);
  }

  public static StructMember newInstance(SModel sm, boolean init) {
    return (StructMember)SModelUtil_new.instantiateConceptDeclaration("mps.samples.architecture.types.structure.StructMember", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static StructMember newInstance(SModel sm) {
    return StructMember.newInstance(sm, false);
  }
}
