package mps.samples.architecture.types.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Typedef extends BaseConcept implements INamedConcept {
  public static final String concept = "mps.samples.architecture.types.structure.Typedef";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String TYPE = "type";

  public Typedef(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(Typedef.NAME);
  }

  public void setName(String value) {
    this.setProperty(Typedef.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(Typedef.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Typedef.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Typedef.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Typedef.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Typedef.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Typedef.VIRTUAL_PACKAGE, value);
  }

  public Type getType() {
    return (Type)this.getChild(Type.class, Typedef.TYPE);
  }

  public void setType(Type node) {
    super.setChild(Typedef.TYPE, node);
  }

  public static Typedef newInstance(SModel sm, boolean init) {
    return (Typedef)SModelUtil_new.instantiateConceptDeclaration("mps.samples.architecture.types.structure.Typedef", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Typedef newInstance(SModel sm) {
    return Typedef.newInstance(sm, false);
  }
}
