package mps.samples.architecture.types.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TypedefReference extends Type {
  public static final String concept = "mps.samples.architecture.types.structure.TypedefReference";
  public static final String TYPEDEF = "typedef";

  public TypedefReference(SNode node) {
    super(node);
  }

  public Typedef getTypedef() {
    return (Typedef)this.getReferent(Typedef.class, TypedefReference.TYPEDEF);
  }

  public void setTypedef(Typedef node) {
    super.setReferent(TypedefReference.TYPEDEF, node);
  }

  public static TypedefReference newInstance(SModel sm, boolean init) {
    return (TypedefReference)SModelUtil_new.instantiateConceptDeclaration("mps.samples.architecture.types.structure.TypedefReference", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TypedefReference newInstance(SModel sm) {
    return TypedefReference.newInstance(sm, false);
  }
}
