package v2.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Cardinality extends BaseConcept {
  public static final String concept = "v2.structure.Cardinality";

  public Cardinality(SNode node) {
    super(node);
  }

  public static Cardinality newInstance(SModel sm, boolean init) {
    return (Cardinality)SModelUtil_new.instantiateConceptDeclaration("v2.structure.Cardinality", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Cardinality newInstance(SModel sm) {
    return Cardinality.newInstance(sm, false);
  }
}
