package v2.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ConnectionEndpoint extends BaseConcept {
  public static final String concept = "v2.structure.ConnectionEndpoint";

  public ConnectionEndpoint(SNode node) {
    super(node);
  }

  public static ConnectionEndpoint newInstance(SModel sm, boolean init) {
    return (ConnectionEndpoint)SModelUtil_new.instantiateConceptDeclaration("v2.structure.ConnectionEndpoint", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ConnectionEndpoint newInstance(SModel sm) {
    return ConnectionEndpoint.newInstance(sm, false);
  }
}
