package v2.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CustomDataStructureMember extends DataStructureMember {
  public static final String concept = "v2.structure.CustomDataStructureMember";
  public static final String CUSTOM_TYPE = "customType";

  public CustomDataStructureMember(SNode node) {
    super(node);
  }

  public DataStructure getCustomType() {
    return (DataStructure)this.getReferent(DataStructure.class, CustomDataStructureMember.CUSTOM_TYPE);
  }

  public void setCustomType(DataStructure node) {
    super.setReferent(CustomDataStructureMember.CUSTOM_TYPE, node);
  }

  public static CustomDataStructureMember newInstance(SModel sm, boolean init) {
    return (CustomDataStructureMember)SModelUtil_new.instantiateConceptDeclaration("v2.structure.CustomDataStructureMember", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CustomDataStructureMember newInstance(SModel sm) {
    return CustomDataStructureMember.newInstance(sm, false);
  }
}
