package v2.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class DataStructureMember extends BaseConcept implements INamedConcept {
  public static final String concept = "v2.structure.DataStructureMember";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";

  public DataStructureMember(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(DataStructureMember.NAME);
  }

  public void setName(String value) {
    this.setProperty(DataStructureMember.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(DataStructureMember.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(DataStructureMember.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(DataStructureMember.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(DataStructureMember.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(DataStructureMember.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(DataStructureMember.VIRTUAL_PACKAGE, value);
  }

  public static DataStructureMember newInstance(SModel sm, boolean init) {
    return (DataStructureMember)SModelUtil_new.instantiateConceptDeclaration("v2.structure.DataStructureMember", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static DataStructureMember newInstance(SModel sm) {
    return DataStructureMember.newInstance(sm, false);
  }
}
