package v2.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class One extends Cardinality {
  public static final String concept = "v2.structure.One";

  public One(SNode node) {
    super(node);
  }

  public static One newInstance(SModel sm, boolean init) {
    return (One)SModelUtil_new.instantiateConceptDeclaration("v2.structure.One", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static One newInstance(SModel sm) {
    return One.newInstance(sm, false);
  }
}
