package v2.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class OneToN extends Cardinality {
  public static final String concept = "v2.structure.OneToN";

  public OneToN(SNode node) {
    super(node);
  }

  public static OneToN newInstance(SModel sm, boolean init) {
    return (OneToN)SModelUtil_new.instantiateConceptDeclaration("v2.structure.OneToN", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static OneToN newInstance(SModel sm) {
    return OneToN.newInstance(sm, false);
  }
}
