package v2.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ProvidedInterfaceConnectionEndpoint extends ConnectionEndpoint {
  public static final String concept = "v2.structure.ProvidedInterfaceConnectionEndpoint";
  public static final String INSTANCE_REFERENCE = "instanceReference";
  public static final String PROVIDED_INTERFACE_REFERENCE = "providedInterfaceReference";

  public ProvidedInterfaceConnectionEndpoint(SNode node) {
    super(node);
  }

  public InstanceReference getInstanceReference() {
    return (InstanceReference)this.getChild(InstanceReference.class, ProvidedInterfaceConnectionEndpoint.INSTANCE_REFERENCE);
  }

  public void setInstanceReference(InstanceReference node) {
    super.setChild(ProvidedInterfaceConnectionEndpoint.INSTANCE_REFERENCE, node);
  }

  public ProvidedInterfaceReference getProvidedInterfaceReference() {
    return (ProvidedInterfaceReference)this.getChild(ProvidedInterfaceReference.class, ProvidedInterfaceConnectionEndpoint.PROVIDED_INTERFACE_REFERENCE);
  }

  public void setProvidedInterfaceReference(ProvidedInterfaceReference node) {
    super.setChild(ProvidedInterfaceConnectionEndpoint.PROVIDED_INTERFACE_REFERENCE, node);
  }

  public static ProvidedInterfaceConnectionEndpoint newInstance(SModel sm, boolean init) {
    return (ProvidedInterfaceConnectionEndpoint)SModelUtil_new.instantiateConceptDeclaration("v2.structure.ProvidedInterfaceConnectionEndpoint", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ProvidedInterfaceConnectionEndpoint newInstance(SModel sm) {
    return ProvidedInterfaceConnectionEndpoint.newInstance(sm, false);
  }
}
