package v2.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ReplicationProperty extends BaseConcept implements INamedConcept {
  public static final String concept = "v2.structure.ReplicationProperty";
  public static final String VALUE = "value";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";

  public ReplicationProperty(SNode node) {
    super(node);
  }

  public String getValue() {
    return this.getProperty(ReplicationProperty.VALUE);
  }

  public void setValue(String value) {
    this.setProperty(ReplicationProperty.VALUE, value);
  }

  public String getName() {
    return this.getProperty(ReplicationProperty.NAME);
  }

  public void setName(String value) {
    this.setProperty(ReplicationProperty.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(ReplicationProperty.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(ReplicationProperty.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(ReplicationProperty.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(ReplicationProperty.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(ReplicationProperty.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(ReplicationProperty.VIRTUAL_PACKAGE, value);
  }

  public static ReplicationProperty newInstance(SModel sm, boolean init) {
    return (ReplicationProperty)SModelUtil_new.instantiateConceptDeclaration("v2.structure.ReplicationProperty", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ReplicationProperty newInstance(SModel sm) {
    return ReplicationProperty.newInstance(sm, false);
  }
}
