package v2.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class RequiredInterfaceReference extends BaseConcept {
  public static final String concept = "v2.structure.RequiredInterfaceReference";
  public static final String REQUIRED_INTERFACE = "requiredInterface";

  public RequiredInterfaceReference(SNode node) {
    super(node);
  }

  public RequiredInterface getRequiredInterface() {
    return (RequiredInterface)this.getReferent(RequiredInterface.class, RequiredInterfaceReference.REQUIRED_INTERFACE);
  }

  public void setRequiredInterface(RequiredInterface node) {
    super.setReferent(RequiredInterfaceReference.REQUIRED_INTERFACE, node);
  }

  public static RequiredInterfaceReference newInstance(SModel sm, boolean init) {
    return (RequiredInterfaceReference)SModelUtil_new.instantiateConceptDeclaration("v2.structure.RequiredInterfaceReference", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static RequiredInterfaceReference newInstance(SModel sm) {
    return RequiredInterfaceReference.newInstance(sm, false);
  }
}
