package v2.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class V2_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("c6af9800-b441-4a73-aee7-d3a6ffa74fd3(v2)");

  public static Language get() {
    return (Language)MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
