package mps.sample.architecture.replicated_datastructures.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Publish extends BaseConcept {
  public static final String concept = "mps.sample.architecture.replicated_datastructures.structure.Publish";
  public static final String REFERENCE = "reference";
  public static final String SPECIFICATION = "specification";

  public Publish(SNode node) {
    super(node);
  }

  public DatastructureReference getReference() {
    return (DatastructureReference)this.getChild(DatastructureReference.class, Publish.REFERENCE);
  }

  public void setReference(DatastructureReference node) {
    super.setChild(Publish.REFERENCE, node);
  }

  public int getSpecificationsCount() {
    return this.getChildCount(Publish.SPECIFICATION);
  }

  public Iterator<ReplicationSpecification> specifications() {
    return this.children(ReplicationSpecification.class, Publish.SPECIFICATION);
  }

  public List<ReplicationSpecification> getSpecifications() {
    return this.getChildren(ReplicationSpecification.class, Publish.SPECIFICATION);
  }

  public void addSpecification(ReplicationSpecification node) {
    this.addChild(Publish.SPECIFICATION, node);
  }

  public void insertSpecification(ReplicationSpecification prev, ReplicationSpecification node) {
    this.insertChild(prev, Publish.SPECIFICATION, node);
  }

  public static Publish newInstance(SModel sm, boolean init) {
    return (Publish)SModelUtil_new.instantiateConceptDeclaration("mps.sample.architecture.replicated_datastructures.structure.Publish", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Publish newInstance(SModel sm) {
    return Publish.newInstance(sm, false);
  }
}
