package mps.sample.architecture.replicated_datastructures.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Replicated_datastructures_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("e71f9d52-3001-4671-b636-fff03fa9aebe(mps.sample.architecture.replicated_datastructures)");

  public static Language get() {
    return (Language)MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
