package mps.sample.architecture.replicated_datastructures.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ReplicationSpecification extends BaseConcept implements INamedConcept {
  public static final String concept = "mps.sample.architecture.replicated_datastructures.structure.ReplicationSpecification";
  public static final String VALUE = "value";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";

  public ReplicationSpecification(SNode node) {
    super(node);
  }

  public String getValue() {
    return this.getProperty(ReplicationSpecification.VALUE);
  }

  public void setValue(String value) {
    this.setProperty(ReplicationSpecification.VALUE, value);
  }

  public String getName() {
    return this.getProperty(ReplicationSpecification.NAME);
  }

  public void setName(String value) {
    this.setProperty(ReplicationSpecification.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(ReplicationSpecification.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(ReplicationSpecification.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(ReplicationSpecification.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(ReplicationSpecification.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(ReplicationSpecification.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(ReplicationSpecification.VIRTUAL_PACKAGE, value);
  }

  public static ReplicationSpecification newInstance(SModel sm, boolean init) {
    return (ReplicationSpecification)SModelUtil_new.instantiateConceptDeclaration("mps.sample.architecture.replicated_datastructures.structure.ReplicationSpecification", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ReplicationSpecification newInstance(SModel sm) {
    return ReplicationSpecification.newInstance(sm, false);
  }
}
