package mps.sample.architecture.replicated_datastructures.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ReplicatedSingleton extends ReplicatedDatastructure {
  public static final String concept = "mps.sample.architecture.replicated_datastructures.structure.ReplicatedSingleton";

  public ReplicatedSingleton(SNode node) {
    super(node);
  }

  public static ReplicatedSingleton newInstance(SModel sm, boolean init) {
    return (ReplicatedSingleton)SModelUtil_new.instantiateConceptDeclaration("mps.sample.architecture.replicated_datastructures.structure.ReplicatedSingleton", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ReplicatedSingleton newInstance(SModel sm) {
    return ReplicatedSingleton.newInstance(sm, false);
  }
}
